### ISSUE TITLE
Wrong documentation on getting session handle

### ISSUE THREAD

**Issue by paulmega1** [supertokens/supertokens-laravel#17]
Hey guys, working with the API frist time, having a good time so far.

However, I did find what I think is a mistake in the documentation on https://supertokens.io/docs/laravel/usage/session-handle .

The page describes using `->getSessionHandle()` as the way to get a session's handle - however my Laravel didn't work with that command. I dug through the code and found that `->getHandle()` is the right command. Took me a little while to figure out though. Aside from that the documentation could also mention getting the session data from the request first as well.

I'd suggest changing the first code entry on the page to:

```php
$session = $request->supertokens;
$handle = $session->getToken();
```

Aside from that I'm very happy with the documentation so far.

**Comment by rishabhpoddar** [comment]
Thank you @paulmega1. Will make this change ASAP!

**Comment by rishabhpoddar** [comment]
The docs have been fixed. If you are still seeing the older version, it's probably to do with caching :)

Thanks once again for pointing this out.
