### ISSUE TITLE
Create `front-token` and send it whenever sending access token to the frontend

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-laravel#5]
The `front-token` allows you to read user id and jwt payload securely from the frontend without exposing the access token

- In this [file](https://github.com/supertokens/supertokens-laravel/blob/master/src/Helpers/CookieAndHeader.php) create the `attachFrontTokenToHeader` function similar to the one defined [here](https://github.com/supertokens/supertokens-node/blob/master/lib/ts/cookieAndHeaders.ts#L215).
- The `attachFrontTokenToHeader` function should set the `frontTokenHeaderKey` and `tokenInfo` in the header. The `front-token` should be exposed by setting `front-token` as the value of the `Access-Control-Expose-Headers` key in the header.
- Make sure that whenever the access token is attached to the response the `front-token` is also attached, this will be done by calling the `attachFrontTokenToHeader` function.

Run all the tests and make sure that they all pass.

**Comment by ocReaper** [comment]
I'm working on it!

**Comment by rishabhpoddar** [comment]
@ocReaper thanks! I have assigned this issue to you.

**Comment by ocReaper** [comment]
@rishabhpoddar I'm ready with the code, but do you have a `docker-compose` or a `Dockerfile` so I can run the tests? I'm on Windows currently..

**Comment by rishabhpoddar** [comment]
@ocReaper. Unfortunately, the tests are not setup to work with a Dockerised core :(

Feel free to issue a PR. I can test the code for you.
