### ISSUE TITLE
(Easy) Possibility of double setting of access token cookie

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-laravel#6]
We need to make sure that in the [setCookie function](https://github.com/supertokens/supertokens-laravel/blob/master/src/Helpers/CookieAndHeader.php#L105), if given the same cookie twice, it does not set it two times. Instead, the older cookie should be overwritten by the new cookie.

For example, if I call setCookie with a cookie like `abc=someVal`, and then I call it again with a cookie like `abc=someOtherVal`, the final response should have just `Set-Cookie: abc=someOtherVal` and NOT `Set-Cookie: abc=someOtherVal; abc=someVal`

Note that the overwrite only applies to cookies with that have already been set in the response. If there are other cookies that exist already, and a new cookie (with a new key) is being added, the previous ones should not be overwritten.

**Comment by Devsome** [comment]
I would need some more information.

**Comment by rishabhpoddar** [comment]
Hey @Devsome. I have updated the description of this issue. I'll assign this issue to you for now

**Comment by rishabhpoddar** [comment]
@Devsome , are you still working on this issue? If yes, I will reassign it to you

**Comment by IsautierEloise** [comment]
Can you assign this to me please ?

**Comment by rishabhpoddar** [comment]
Hi @IsautierEloise I have assigned this issue to you. Thank you

**Comment by IsautierEloise** [comment]
Sorry, I am a beginner, I have trouble understanding how to call setCookie twice and get one response ? Do you have an example ?

**Comment by rishabhpoddar** [comment]
Hi @IsautierEloise ,
The `setCookie` function takes a `Response` object as its first param. It modifies that object within the function. So calling that function twice with the same `Response` object, would set two cookies in the same response.

If the cookies being set (for the same `Response` object) have the same key, then we see the problem that this issue is for.

**Comment by IsautierEloise** [comment]
Hello ! I have been trying to create the problem but to me, the function already works as described. 
Here you can see I call the setCookies() function twice on the same response, changing only the value : 
<img width="975" alt="Screenshot 2020-10-27 at 10 35 30" src="https://user-images.githubusercontent.com/44578188/97283636-5fd99280-1840-11eb-99f6-b92d15f4f60a.png">

And in the response the value is correctly overwritten : 
<img width="964" alt="Screenshot 2020-10-27 at 10 35 41" src="https://user-images.githubusercontent.com/44578188/97283708-754ebc80-1840-11eb-927e-44964e8d7232.png">

**Comment by rishabhpoddar** [comment]
Oh! Interesting.. so this is a false issue then. Then all we need are tests for this, and if the tests pass with no code change, then it works!

The tests:
- setting a single cookie and checking the output contains that
- setting two different cookies and checking the output contains both
- setting a cookie two times, and checking that the output contains only the cookie set the second time
- setting two different cookies, and then overwriting one of them and then checking that the output is correct

**Comment by IsautierEloise** [comment]
https://github.com/supertokens/supertokens-laravel/pull/12
